create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  subcategory text not null default '',
  emoji text not null default '',
  image text not null default '',
  description text not null default '',
  price integer not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique,
  order_date text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  shipping_zone text not null,
  payment_method text not null,
  items jsonb not null default '[]'::jsonb,
  shipping_fee integer not null default 0 check (shipping_fee >= 0),
  total integer not null default 0 check (total >= 0),
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();
