export const INITIAL_PRODUCTS = [
  {
    id: 1,
    n: "Soap & Glory Vanilla-Licious Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/soap-glory-vanilla-licious-body-lotion.webp",
    d: "Lait corporel parfum vanille crémeuse et musc exotique, à la texture légère pour hydrater et adoucir la peau.",
    p: 9500,
    s: 8,
  },
  {
    id: 2,
    n: "Soap & Glory Vanilla-Licious Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/soap-glory-vanilla-licious-body-wash.webp",
    d: "Gel douche à la vanille crémeuse et au musc exotique, pour nettoyer tout en laissant la peau confortable.",
    p: 9000,
    s: 7,
  },
  {
    id: 3,
    n: "Palmer's Cocoa Butter Formula Tummy Butter",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/palmers-tummy-butter-official.png",
    d: "Beurre riche au cacao, collagène, élastine et huiles nourrissantes, pensé pour les zones sujettes aux vergetures.",
    p: 8500,
    s: 6,
  },
  {
    id: 4,
    n: "Vaseline Healthy Bright Gluta-Hya Dewy Radiance",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-gluta-hya-dewy-radiance-official.jpg",
    d: "Sérum-en-lotion à l'hyaluron et niacinamide pour une peau visiblement plus rebondie, lumineuse et confortable.",
    p: 6500,
    s: 12,
  },
  {
    id: 5,
    n: "Vaseline Healthy Bright Gluta-Hya Flawless Glow",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-gluta-hya-flawless-glow-official.png",
    d: "Sérum-en-lotion éclat avec hyaluron et pro-retinol, pour un toucher non collant et un fini uniforme.",
    p: 6500,
    s: 11,
  },
  {
    id: 6,
    n: "Dr Teal's Body Lotion Citrus Essential Oils",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/dr-teals-citrus-body-lotion-official.jpg",
    d: "Lotion corps aux huiles essentielles d'agrumes, beurre de karité et cacao pour nourrir et réveiller l'éclat.",
    p: 8500,
    s: 9,
  },
  {
    id: 7,
    n: "Face Facts Ceramide Moisturising Cream",
    c: "visage",
    e: "🫙",
    i: "/catalog/officiel/face-facts-ceramide-moisturising-cream.jpg",
    d: "Crème 2-en-1 visage et corps avec 5 céramides, acide hyaluronique et avoine pour renforcer la barrière cutanée.",
    p: 7000,
    s: 10,
  },
  {
    id: 8,
    n: "Advanced Clinicals Retinol Advanced Firming Cream",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/advanced-clinicals-retinol-firming-cream-official.jpg",
    d: "Crème raffermissante au rétinol enrichie en aloe vera, camomille et thé vert pour lisser et hydrater.",
    p: 14500,
    s: 5,
  },
  {
    id: 9,
    n: "Mixa Crème Cica Réparation 10% Urée + Niacinamide",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/mixa-cica-reparation-uree-niacinamide.webp",
    d: "Soin réparateur lissant pour peaux sèches et fragilisées, formulé avec 10% d'urée et niacinamide.",
    p: 8000,
    s: 8,
  },
  {
    id: 10,
    n: "Byphasse Crème Hydratante Huile d'Amande Douce",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/byphasse-creme-hydratante-amande-official.png",
    d: "Crème corporelle onctueuse à l'huile d'amande douce, glycérine et vitamine E pour nourrir les peaux sèches.",
    p: 6500,
    s: 13,
  },
  {
    id: 11,
    n: "Byphasse Crème Hydratante Huile de Coco",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/byphasse-creme-hydratante-coco-official.png",
    d: "Crème hydratante corporelle à l'huile de coco, conçue pour apporter souplesse et confort au quotidien.",
    p: 6500,
    s: 13,
  },
  {
    id: 12,
    n: "Medix 5.5 Vitamin C + Turmeric Body Cream",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/medix-vitamin-c-turmeric-body-cream-official.jpg",
    d: "Crème corps illuminateur à la vitamine C et au curcuma, pensée pour raviver l'éclat et améliorer l'uniformité.",
    p: 14500,
    s: 7,
  },
  {
    id: 13,
    n: "Dexeryl Crème",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/dexeryl-creme-official.png",
    d: "Crème émolliente pour sécheresse cutanée, formulée avec glycérine, vaseline et paraffine liquide.",
    p: 10000,
    s: 9,
  },
  {
    id: 14,
    n: "Palmer's Cocoa Butter Heals & Softens",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/palmers-heals-softens-body-lotion.jpg",
    d: "Lotion quotidienne au beurre de cacao et vitamine E pour soulager la sécheresse et garder la peau souple.",
    p: 9500,
    s: 8,
  },
  {
    id: 15,
    n: "Palmer's Firms & Tones Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/palmers-firms-tones-body-lotion.webp",
    d: "Lotion raffermissante au beurre de cacao et collagène pour améliorer la tonicité des peaux relâchées.",
    p: 9800,
    s: 6,
  },
  {
    id: 16,
    n: "Palmer's Smooth & Radiant Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/palmers-smooth-radiant-body-lotion.jpg",
    d: "Lotion exfoliante douce pensée pour lisser le grain de peau et révéler un fini plus lumineux.",
    p: 9800,
    s: 5,
  },
  {
    id: 17,
    n: "Palmer's Raw Shea Nourish Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/palmers-raw-shea-nourish-body-lotion.jpg",
    d: "Lotion nourrissante au karité brut et vitamine E pour hydrater intensément les peaux sèches.",
    p: 9800,
    s: 7,
  },
  {
    id: 18,
    n: "CeraVe SA Smoothing Cream",
    c: "corps",
    e: "🫙",
    i: "/catalog/officiel/cerave-sa-smoothing-cream-official.jpg",
    d: "Crème lissante à l'acide salicylique, urée et céramides pour les peaux sèches, rugueuses ou squameuses.",
    p: 12500,
    s: 6,
  },
  {
    id: 19,
    n: "CeraVe Daily Moisturizing Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/cerave-daily-moisturizing-lotion-official.png",
    d: "Lotion hydratante légère avec 3 céramides essentiels et acide hyaluronique pour restaurer la barrière cutanée.",
    p: 11500,
    s: 8,
  },
  {
    id: 20,
    n: "Byphasse Lait Corporel Nutritif Amande Douce",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/byphasse-lait-corporel-amande-official.png",
    d: "Lait corporel nourrissant à l'huile d'amande douce, idéal pour adoucir les peaux sèches sans effet lourd.",
    p: 6000,
    s: 14,
  },
  {
    id: 21,
    n: "Vaseline Healthy Bright Daily Brightening",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-healthy-bright-daily-brightening-official.jpg",
    d: "Lotion éclaircissante à la vitamine B3 et gelée Vaseline, pour unifier visuellement le teint du corps.",
    p: 7000,
    s: 10,
  },
  {
    id: 22,
    n: "Aveeno Daily Moisturizing Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/aveeno-daily-moisturizing-body-lotion-official.jpg",
    d: "Lotion corporelle à l'avoine prébiotique pour hydrater intensément les peaux sèches pendant 24 heures.",
    p: 11000,
    s: 7,
  },
  {
    id: 23,
    n: "Medix 5.5 Retinol + Ferulic Acid Body Cream",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/medix-retinol-ferulic-body-cream-official.jpg",
    d: "Crème corps au rétinol et acide férulique pour lisser l'aspect de la peau et améliorer le confort.",
    p: 14500,
    s: 5,
  },
  {
    id: 24,
    n: "Garnier Soothing Hyaluronic Aloe Cream Cleanser",
    c: "visage",
    e: "🫧",
    i: "/catalog/officiel/garnier-soothing-hyaluronic-aloe-cream-cleanser-official.png",
    d: "Nettoyant crème à l'aloe et acide hyaluronique qui nettoie en douceur, hydrate et apaise la peau.",
    p: 6000,
    s: 10,
  },
  {
    id: 25,
    n: "Garnier Brightening Vitamin C Cream Cleanser",
    c: "visage",
    e: "🫧",
    i: "/catalog/officiel/garnier-brightening-vitamin-c-cream-cleanser-official.png",
    d: "Nettoyant crème à la vitamine C pour raviver l'éclat, éliminer les impuretés et soutenir la barrière cutanée.",
    p: 6000,
    s: 10,
  },
  {
    id: 26,
    n: "Topicrem Ultra-Hydratant Lait Corps",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/topicrem-ultra-hydratant-lait-corps-official.jpg",
    d: "Lait corps hydratant à l'urée et à la glycérine pour protéger durablement les peaux sèches et sensibles.",
    p: 12000,
    s: 6,
  },
  {
    id: 27,
    n: "Jergens Ultra Healing Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/jergens-ultra-healing-body-lotion-official.jpg",
    d: "Lotion réparatrice pour peaux extra sèches, formulée pour hydrater en profondeur et restaurer la douceur.",
    p: 9500,
    s: 8,
  },
  {
    id: 28,
    n: "Jergens Original Scent Cherry Almond",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/jergens-cherry-almond-body-lotion-official.jpg",
    d: "Lotion iconique parfum cerise-amande, légère et soyeuse, pour une peau douce et délicatement parfumée.",
    p: 9500,
    s: 8,
  },
  {
    id: 29,
    n: "AmLactin Rapid Relief 15% Lactic Acid",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/amlactin-rapid-relief-official.jpg",
    d: "Lotion restauratrice à 15% d'acide lactique pour atténuer la rugosité et soutenir le renouvellement cutané.",
    p: 15000,
    s: 5,
  },
  {
    id: 30,
    n: "AmLactin Daily 12% Lactic Acid Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/amlactin-daily-12-lactic-lotion-official.jpg",
    d: "Lotion quotidienne à 12% d'acide lactique pour lisser, hydrater et améliorer les peaux sèches et rêches.",
    p: 14500,
    s: 5,
  },
  {
    id: 31,
    n: "Vaseline Intensive Care Almond Smooth",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-almond-smooth-official.webp",
    d: "Lotion à l'huile d'amande et vitamine E pour nourrir la peau sèche sans sensation grasse.",
    p: 7000,
    s: 11,
  },
  {
    id: 32,
    n: "Vaseline Intensive Care Dry Skin Repair",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-dry-skin-repair-official.jpg",
    d: "Lotion riche à l'avoine pour soulager la sécheresse sévère et maintenir l'hydratation jusqu'à 72 heures.",
    p: 7500,
    s: 10,
  },
  {
    id: 33,
    n: "Vaseline Intensive Care Cocoa Radiant",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/vaseline-cocoa-radiant-lotion-official.jpg",
    d: "Lotion au beurre de cacao et micro-gouttes de gelée Vaseline pour hydrater et illuminer les peaux ternes.",
    p: 7500,
    s: 12,
  },
  {
    id: 34,
    n: "Queen Helene Cocoa Butter Hand + Body Lotion",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/queen-helene-cocoa-butter-lotion-official.jpg",
    d: "Lotion mains et corps au beurre de cacao pour assouplir les zones sèches et redonner du confort.",
    p: 6500,
    s: 9,
  },
  {
    id: 35,
    n: "Topicrem Ultra-Hydratant Gel Douche",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/topicrem-ultra-hydratant-gel-douche.jpg",
    d: "Gel douche à la glycérine végétale pour peaux sensibles et sèches, qui nettoie en douceur et aide à prévenir le dessèchement.",
    p: 7500,
    s: 9,
  },
  {
    id: 36,
    n: "F&W Mix Ready 2 Glow Shower Gel",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/fw-mix-ready-2-glow.png",
    d: "Gel douche exfoliant illuminateur conçu pour nettoyer, lisser le grain de peau et raviver l'éclat.",
    p: 7000,
    s: 8,
  },
  {
    id: 37,
    n: "F&W Original Glutathion Shower Gel",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/fw-original-glutathion.jpg",
    d: "Gel douche exfoliant au glutathion et à la vitamine C pour une peau plus nette, douce et lumineuse.",
    p: 7000,
    s: 8,
  },
  {
    id: 38,
    n: "Method Body Pure Peace",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/method-pure-peace.jpg",
    d: "Gel douche au parfum rose, pivoine et sel rose, formulé avec des agents hydratants d'origine végétale.",
    p: 8500,
    s: 6,
  },
  {
    id: 39,
    n: "Method Body Simply Nourish",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/method-simply-nourish.jpg",
    d: "Gel douche cocooning à la noix de coco, au lait de riz et au beurre de karité pour nettoyer sans décaper.",
    p: 8500,
    s: 7,
  },
  {
    id: 40,
    n: "Medix 5.5 Glycolic + Lactic Acid Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/medix-glycolic-lactic-body-wash.jpg",
    d: "Gel douche aux acides glycolique et lactique pour exfolier en douceur et améliorer l'aspect des zones rugueuses.",
    p: 14500,
    s: 5,
  },
  {
    id: 41,
    n: "Saltair Golden Hour Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/saltair-golden-hour.jpg",
    d: "Gel douche nourrissant infusé d'huile de fruit de la passion pour laisser la peau souple et confortable.",
    p: 11000,
    s: 6,
  },
  {
    id: 42,
    n: "Saltair Pink Beach Serum Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/saltair-pink-beach.jpg",
    d: "Gel douche sérum adoucissant à l'esprit coco, pensé pour une mousse douce et une peau soyeuse.",
    p: 11000,
    s: 6,
  },
  {
    id: 43,
    n: "Saltair Exotic Pulp Serum Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/saltair-exotic-pulp.jpg",
    d: "Gel douche sérum illuminateur aux notes fruitées pour nettoyer et réveiller l'éclat du corps.",
    p: 11000,
    s: 6,
  },
  {
    id: 44,
    n: "Olay Vitamin C Moisturizing Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-vitamin-c-body-wash.jpg",
    d: "Gel douche hydratant à la vitamine C pour une peau visiblement plus lumineuse et confortable après rinçage.",
    p: 10500,
    s: 7,
  },
  {
    id: 45,
    n: "Veetgold Snail White Shower Bath",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/veetgold-snail-white.jpg",
    d: "Shower bath exfoliant enrichi en extraits végétaux pour nettoyer, lisser et adoucir la peau.",
    p: 9000,
    s: 5,
  },
  {
    id: 46,
    n: "Veetgold Coffee & Coconut Shower Bath",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/veetgold-coffee-coconut.jpg",
    d: "Gel douche gommant café et coco pour nettoyer, exfolier et laisser la peau plus souple.",
    p: 9000,
    s: 5,
  },
  {
    id: 47,
    n: "Veetgold Sugar & Milk Body Magic",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/veetgold-sugar-milk.jpg",
    d: "Shower bath corps au sucre et au lait, pensé pour lisser la peau et améliorer sa douceur au quotidien.",
    p: 9000,
    s: 5,
  },
  {
    id: 48,
    n: "Dr. Bronner's Peppermint Pure-Castile Magic Soap",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/drbronner-peppermint.png",
    d: "Savon liquide multi-usage à la menthe poivrée, biodégradable, apprécié pour sa mousse fraîche et sa formule concentrée.",
    p: 14000,
    s: 4,
  },
  {
    id: 49,
    n: "F&W Original Black Soap Shower Gel",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/fw-original-black-soap.jpg",
    d: "Gel douche exfoliant au cacao, acide salicylique et extrait de karité pour purifier et raviver l'éclat.",
    p: 7000,
    s: 8,
  },
  {
    id: 50,
    n: "Olay Age Defying Niacinamide Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-niacinamide-body-wash.jpg",
    d: "Gel douche hydratant à la niacinamide pour laisser la peau plus lisse, souple et visiblement reposée.",
    p: 10500,
    s: 6,
  },
  {
    id: 51,
    n: "Olay Cleansing & Renewing Nighttime Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-retinol-body-wash.jpg",
    d: "Gel douche au rétinol et à la vitamine B3 pour nettoyer en douceur tout en soutenant le confort cutané.",
    p: 11000,
    s: 6,
  },
  {
    id: 52,
    n: "Olay Witch Hazel Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-witch-hazel-body-wash.jpg",
    d: "Gel douche clarifiant à l'hamamélis et vitamine B3 pour une sensation de peau fraîche et nette.",
    p: 10500,
    s: 6,
  },
  {
    id: 53,
    n: "Native Coconut & Vanilla Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/native-coconut-vanilla.png",
    d: "Gel douche coco-vanille au profil clean beauty, sans sulfates agressifs ni parabènes.",
    p: 9500,
    s: 7,
  },
  {
    id: 54,
    n: "Olay B3+ Vitamin C Creme Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-b3-vitamin-c-creme-body-wash.jpg",
    d: "Crème lavante à la niacinamide et vitamine C pour nettoyer le corps tout en soutenant l'éclat.",
    p: 11000,
    s: 6,
  },
  {
    id: 55,
    n: "Olay B3+ Hyaluronic Acid Creme Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-b3-hyaluronic-creme-body-wash.png",
    d: "Crème lavante à la niacinamide et à l'acide hyaluronique pour une peau plus souple et rebondie.",
    p: 11000,
    s: 6,
  },
  {
    id: 56,
    n: "Olay B3+ Peptide Creme Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/olay-b3-peptide-creme-body-wash.png",
    d: "Crème lavante à la niacinamide et aux peptides, pensée pour une routine corps axée confort et fermeté.",
    p: 11500,
    s: 6,
  },
  {
    id: 57,
    n: "OGX Coconut Coffee Scrub & Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/ogx-coconut-coffee.webp",
    d: "Scrub & wash exfoliant au café arabica et huile de coco pour lisser, réveiller et hydrater la peau.",
    p: 9500,
    s: 7,
  },
  {
    id: 58,
    n: "OGX Rose Water & Pink Sea Salt Scrub & Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/ogx-rose-water.webp",
    d: "Scrub & wash à l'eau de rose et au sel rose pour exfolier doucement et laisser la peau plus douce.",
    p: 9500,
    s: 7,
  },
  {
    id: 59,
    n: "OGX Sea Kelp & Hyaluronic Acid Scrub & Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/ogx-sea-kelp.webp",
    d: "Scrub & wash hydratant aux algues marines et à l'acide hyaluronique pour exfolier et désaltérer la peau.",
    p: 9800,
    s: 7,
  },
  {
    id: 60,
    n: "G9 Skin Self Aesthetic Soft Hand Mask",
    c: "mains",
    e: "🤲",
    i: "/catalog/officiel/g9-soft-hand-mask.jpg",
    d: "Masque gants nourrissant pour les mains, pensé pour adoucir rapidement les mains sèches et les cuticules.",
    p: 3500,
    s: 10,
  },
  {
    id: 61,
    n: "Frudia My Orchard Hand Cream Set",
    c: "mains",
    e: "🤲",
    i: "/catalog/officiel/frudia-hand-cream-set.png",
    d: "Coffret de crèmes mains Frudia My Orchard avec plusieurs senteurs fruitées pour hydrater les mains au quotidien.",
    p: 8500,
    s: 8,
  },
  {
    id: 62,
    n: "Vaseline Healthy Hands Stronger Nails Hand Cream 75ml",
    c: "mains",
    e: "💅",
    i: "/catalog/officiel/vaseline-healthy-hands-stronger-nails-75ml-exact.png",
    d: "Crème mains à la kératine pour hydrater les mains sèches tout en aidant à renforcer l'apparence des ongles.",
    p: 4500,
    s: 11,
  },
  {
    id: 63,
    n: "Mixa Crème Mains Réparatrice",
    c: "mains",
    e: "🤲",
    i: "/catalog/officiel/mixa-creme-mains-reparatrice.jpg",
    d: "Crème mains réparatrice à l'allantoïne pour mains abîmées, formulée pour nourrir et apaiser durablement.",
    p: 4500,
    s: 9,
  },
  {
    id: 64,
    n: "Mixa Crème Mains Protectrice Antidessèchement",
    c: "mains",
    e: "🤲",
    i: "/catalog/officiel/mixa-creme-mains-protectrice.jpg",
    d: "Crème mains protectrice pensée pour hydrater, nourrir et limiter le dessèchement au quotidien.",
    p: 4500,
    s: 9,
  },
  {
    id: 65,
    n: "Oral-B Vitality Pro Protect X Clean",
    c: "buccal",
    e: "🪥",
    i: "/catalog/officiel/oral-b-vitality-pro.jpg",
    d: "Brosse a dents electrique Oral-B avec minuterie integree et plusieurs modes de brossage pour un nettoyage regulier.",
    p: 16000,
    s: 5,
  },
  {
    id: 66,
    n: "Portable Oral Irrigator PPS",
    c: "buccal",
    e: "🦷",
    i: "/catalog/officiel/oral-irrigator-pps.png",
    d: "Irrigateur buccal portable avec reservoir compact et embouts interchangeables pour completer le nettoyage dentaire.",
    p: 18000,
    s: 4,
  },
  {
    id: 67,
    n: "Listerine Cool Mint Mouthwash",
    c: "buccal",
    e: "🫗",
    i: "/catalog/officiel/listerine-cool-mint.jpg",
    d: "Bain de bouche antiseptique saveur menthe fraiche pour rafraichir l'haleine et completer la routine bucco-dentaire.",
    p: 6500,
    s: 12,
  },
  {
    id: 68,
    n: "Butcher Boy 100% Pure Refined Coconut Oil",
    c: "divers",
    e: "🥥",
    i: "/catalog/officiel/butcher-boy-coconut-oil.jpg",
    d: "Huile de coco raffinee en format pot, utile en routine multi-usage selon les besoins du quotidien.",
    p: 4000,
    s: 10,
  },
  {
    id: 69,
    n: "Listerine Grapefruit Rose Zero Alcohol Mouthwash",
    c: "buccal",
    e: "🫗",
    i: "/catalog/officiel/listerine-grapefruit-rose.jpg",
    d: "Bain de bouche sans alcool au pamplemousse rose pour une bouche fraiche avec une sensation plus douce.",
    p: 5000,
    s: 8,
  },
  {
    id: 70,
    n: "Listerine Total Care 6-in-1 Clean Mint",
    c: "buccal",
    e: "🫗",
    i: "/catalog/officiel/listerine-total-care.jpg",
    d: "Bain de bouche multi-benefices pour usage quotidien, pense pour rafraichir, nettoyer et completer l'hygiene buccale.",
    p: 6500,
    s: 8,
  },
  {
    id: 71,
    n: "Neutrogena Norwegian Formula Lipcare SPF 20",
    c: "visage",
    e: "💋",
    i: "/catalog/officiel/neutrogena-lipcare-spf20.png",
    d: "Stick levres avec SPF 20 pour aider a proteger et adoucir les levres seches ou gercees.",
    p: 3500,
    s: 10,
  },
  {
    id: 72,
    n: "Ariel All-in-1 PODS Color+",
    c: "divers",
    e: "🧺",
    i: "/catalog/officiel/ariel-all-in-1-pods-color.jpg",
    d: "Capsules lessive tout-en-un pour linge colore, pratique pour le lavage quotidien en machine.",
    p: 6500,
    s: 7,
  },
  {
    id: 73,
    n: "Vanish Oxi Action Colour Safe",
    c: "divers",
    e: "🧼",
    i: "/catalog/officiel/vanish-oxi-action-colour-safe.jpg",
    d: "Detachant textile pour couleurs, concu pour aider a traiter les taches sans chlore.",
    p: 6000,
    s: 7,
  },
  {
    id: 74,
    n: "Eau Écarlate Décolor Stop 2-en-1",
    c: "divers",
    e: "👕",
    i: "/catalog/officiel/eau-ecarlate-decolor-stop.jpg",
    d: "Lingettes anti-decoloration pour aider a proteger et raviver les couleurs au lavage.",
    p: 4500,
    s: 9,
  },
  {
    id: 75,
    n: "Palmer's Brazilian Coco Firming Bum, Bust & Body Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/palmers-brazilian-coco-body-oil.webp",
    d: "Huile corps au coco bresilien et vitamine E pour nourrir, lisser et laisser la peau plus souple.",
    p: 9500,
    s: 6,
  },
  {
    id: 76,
    n: "Palmer's Tahitian Vanilla Moisture Drenching Body Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/palmers-tahitian-vanilla-body-oil.webp",
    d: "Huile corps a la vanille tahitienne pour envelopper la peau d'un voile nourrissant et satine.",
    p: 9500,
    s: 6,
  },
  {
    id: 77,
    n: "L'Occitane Huile de Douche Amande",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/loccitane-amande-shower-oil.png",
    d: "Huile de douche a l'amande qui nettoie en douceur et laisse la peau souple et confortable.",
    p: 13000,
    s: 5,
  },
  {
    id: 78,
    n: "Dexeryl Essentiel Huile de Douche Apaisante",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/dexeryl-essentiel-shower-oil.jpg",
    d: "Huile de douche apaisante pour peaux tres seches, formulee pour nettoyer sans agresser.",
    p: 11000,
    s: 6,
  },
  {
    id: 79,
    n: "Veetgold Gluta White x10 Rapid White Oil SPF 15",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/veetgold-gluta-white-x10.jpg",
    d: "Huile corps Veetgold gluta white x10, proposee pour illuminer visuellement la peau et la laisser plus souple.",
    p: 9500,
    s: 7,
  },
  {
    id: 80,
    n: "Byphasse Huile Demaquillante Douceur Vitamine E",
    c: "visage",
    e: "🧴",
    i: "/catalog/officiel/byphasse-cleansing-oil-official.png",
    d: "Huile demaquillante visage et yeux a la vitamine E pour dissoudre maquillage et impuretes en douceur.",
    p: 6500,
    s: 8,
  },
  {
    id: 81,
    n: "X-White Paris Gluta White x10 Face & Body Corrector Oil SPF 50",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/x-white-paris-gluta-white-x10.jpg",
    d: "Huile correctrice visage et corps X-White Gluta White x10, presentee comme soin glow et correcteur corporel.",
    p: 9500,
    s: 6,
  },
  {
    id: 82,
    n: "Veetgold Turmeric Super Whitening Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/veetgold-turmeric-oil.jpg",
    d: "Huile corps au curcuma proposee pour nourrir et donner un fini lumineux a la peau.",
    p: 9500,
    s: 7,
  },
  {
    id: 83,
    n: "Skin Doctor Paris Gluta Glow Ultra Radiance Body & Face Oil SPF 30",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/skin-doctor-gluta-glow-oil.jpg",
    d: "Huile corps et visage Skin Doctor Gluta Glow, formulee pour nourrir la peau et laisser un fini plus lumineux.",
    p: 9000,
    s: 6,
  },
  {
    id: 84,
    n: "Vaseline Intensive Care Vitamin B3 Body Oil Healthy Even Tone",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/vaseline-vitamin-b3-body-oil.jpg",
    d: "Huile corps Vaseline a la vitamine B3 pour aider a laisser la peau plus douce et lumineuse.",
    p: 8500,
    s: 9,
  },
  {
    id: 85,
    n: "Mixa Huile Anti-Vergetures",
    c: "corps",
    e: "🧴",
    i: "/catalog/officiel/mixa-huile-anti-vergetures.jpg",
    d: "Huile de soin anti-vergetures pour masser les zones ciblees et nourrir la peau.",
    p: 9000,
    s: 7,
  },
  {
    id: 86,
    n: "Vaseline Intensive Care Cocoa Radiant Body Gel Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/vaseline-cocoa-radiant-body-gel-oil-target.jpg",
    d: "Gel oil au cacao pour sceller l'hydratation et apporter un fini confortable sur la peau.",
    p: 8500,
    s: 8,
  },
  {
    id: 87,
    n: "Medix 5.5 Argan Oil + Vitamin E Body Cream",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/medix-argan-vitamin-e-body-cream-official.jpg",
    d: "Crème corps Medix 5.5 a l'huile d'argan et vitamine E, pensee pour nourrir, lisser et soulager la sécheresse.",
    p: 12000,
    s: 5,
  },
  {
    id: 88,
    n: "Vaseline Glazed & Glisten Sunlit Glow Body Gel Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/vaseline-sunlit-glow-target.jpg",
    d: "Gel oil scintillant au fini rose-champagne pour apporter un glow léger et lumineux sur la peau du corps.",
    p: 9000,
    s: 7,
  },
  {
    id: 89,
    n: "Vaseline Glazed & Glisten Golden Hour Glow Body Gel Oil",
    c: "corps",
    e: "✨",
    i: "/catalog/officiel/vaseline-golden-hour-glow-target.jpg",
    d: "Gel oil scintillant a l'effet bronze pour laisser la peau satinee, lumineuse et subtilement doree.",
    p: 9000,
    s: 7,
  },
  {
    id: 90,
    n: "Byphasse Gel Douche Dermo Micellaire Argan",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/byphasse-dermo-micellaire-argan-official.png",
    d: "Gel douche dermo micellaire a l'argan pour nettoyer en douceur tout en gardant la peau confortable.",
    p: 7000,
    s: 8,
  },
  {
    id: 91,
    n: "Irish Spring Original Clean Face + Body Wash",
    c: "corps",
    e: "🫧",
    i: "/catalog/officiel/irish-spring-original-clean.jpg",
    d: "Gel lavant corps et visage a la senteur fraiche, format familial pour l'usage quotidien.",
    p: 7000,
    s: 8,
  },
  {
    id: 92,
    n: "Palmer's Coconut Oil Formula Protect + Hydrate Lip Duo",
    c: "visage",
    e: "💋",
    i: "/catalog/officiel/palmers-coconut-oil-lip-duo.jpg",
    d: "Duo levres Palmer's avec baume SPF 15 et swivel stick a l'huile de coco pour nourrir et proteger.",
    p: 4500,
    s: 9,
  },
];
